### ISSUE TITLE
Verifikasjon av sertifikat på testserver feiler

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/ratatouille#692]
Nedlasting av filer feiler:

   { FetchError: request to https://nintest.artsdatabanken.no/ failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/home/b/src/adb/kverna/node_modules/node-fetch/lib/index.js:1345:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  message: 'request to https://nintest.artsdatabanken.no/ failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' } 

Ser ut som det kan være noe relatert til at vi har en proxy? https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

**Comment by bjornreppen** [comment]
https://www.digicert.com/help/

**Comment by bjornreppen** [comment]
This issue still persists:

wget https://nintest.artsdatabanken.no/basemap/openstreetmap/5/15/8
--2018-10-15 09:26:53--  https://nintest.artsdatabanken.no/basemap/openstreetmap/5/15/8
Resolving nintest.artsdatabanken.no (nintest.artsdatabanken.no)... 158.38.128.51
Connecting to nintest.artsdatabanken.no (nintest.artsdatabanken.no)|158.38.128.51|:443... connected.
ERROR: cannot verify nintest.artsdatabanken.no's certificate, issued by ‘CN=TERENA SSL CA 3,O=TERENA,L=Amsterdam,ST=Noord-Holland,C=NL’:
  Unable to locally verify the issuer's authority.
